version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  sample:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build

jobs:
  build:  # This is the name of the job, feel free to change it to better match what you're trying to do!
    # Change the version below to your required version of python
    docker:
      - image: cimg/python:3.8
      # - image: circleci/python:3.6.1
    working_directory: ~/repo
  
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # Fallback to  using the latest cache if no exec match is found
            - v1-dependencies-
  
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  
      - run:
          name: Run lint
          # This assumes pytest is installed via the install-package step above
          command: |
            . venv/bin/activate
            make lint
